services:
  papermc:
    build: .
    image: papermc-whitelist:latest
    container_name: paper-dev
    ports:
      - "25565:25565"
    volumes:
      - papermc_data:/server_data
    environment:
      EULA: "TRUE"
    restart: unless-stopped

volumes:
  papermc_data: