# ++ Advanced Whitelist Plugin ++
# by blackNinja46

Language: en # Supported Languages: en, de (Default: en)

RequestsExpiration: 10 # in minutes (Default: 10)

Discord-Bot: # The Discord Integration for Manging the Whitelist on your Discord Server
  Enabled: false # Enable Discord Bot
  Token: "" # Discord Bot Token